name: Build and Publish Javascore Contracts

on:
  push:
    branches:
      - "main"

jobs:
  deploy-contracts-uat:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Build Javascore
        working-directory: contracts/javascore
        run: |
          ./gradlew clean build 
          ./gradlew optimizedJar
          ./gradlew zipOutputJars

      - name: Archive artifacts
        uses: actions/upload-artifact@v2
        with:
          name: javascore-contracts
          path: ./contracts/javascore/build/xcall-output-jars.zip
          if-no-files-found: error
          
